micronaut:
  application:
    name: teams-svc
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: ${TEAMS_PORT:8081}
datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:teams}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:teams}
    password: ${POSTGRES_PASSWORD:Password1}
    schema-generate: NONE
    dialect: Postgres
jpa:
  default:
    properties:
      hbm2ddl:
        auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialiect
    packages-to-scan: 'com.wspfeiffer.teams.domain'
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    status:
      http-mapping:
        UP: 200
        UNKNOWN: 200
        DOWN: 503
    sensitive: false
