micronaut:
  application:
    name: employees-svc
datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:employees}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:employees}
    password: ${POSTGRES_PASSWORD:Password1}
    schema-generate: NONE
    dialect: Postgres
jpa:
  default:
    properties:
      hbm2ddl:
        auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialiect
    packages-to-scan: 'com.wspfeiffer.employees.domain'
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    status:
      http-mapping:
        UP: 200
        UNKNOWN: 200
        DOWN: 503
    sensitive: false


